# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Start Bootstrap
email: berkaybora@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Marketer
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: 
github_username:  boraberkay
facebook_username: 
#instagram_username: 
#stackoverflow_url: 
#googleplus_username: 
#skype_username: 
#linkedin_url: https://www.linkedin.com/in/berkaybora/

# Address information
address_street: 
address_city: 
address_state: 
address_zip: 

# Build settings
markdown: kramdown
